version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/action
    overwrite: yes

permissions:
  - object: /
    pattern: "**"

hooks:
  ApplicationStart:
    - location: /home/ubuntu/action/deploy.sh
      timeout: 60
      runas: ubuntu