spring:
  profiles:
    include: API-KEY
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            scope: profile_nickname, account_email, birthday, gender
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-id: "${KAKAO_REST_KEY}"
            client-secret: "${KAKAO_CLIENT_SECRET_KEY}"
            client-authentication-method: POST

          naver:
            client-name: Naver
            scope: name, email, nickname, gender, birthday
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            client-id: "${NAVER_CLIENT_ID}"
            client-secret: "${NAVER_CLIENT_SECRET}"

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            user-name-attribute: id
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-name-attribute: response
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me


  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      #      show_sql: true
      format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      force-response: true
      enabled: true
  tomcat:
    uri-encoding: UTF-8

cloud:
  aws:
    credentials:
      accessKey: "${AWS_ACCESS_KEY}"
      secretKey: "${AWS_SECERT_KEY}"
    s3:
      bucket: timeseller-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false